# Site settings
title: Grace Khieu
tagline: raw. organic. genuine.
logo-fa-class: fa-camera
description: > # this means to ignore newlines until "baseurl:"
  life is fun
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site

# Plugins
gems: ["jekyll-paginate"]

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

# Pagination
paginate: 4
paginate_path: "/blog/page:num/"
